name: API Calls

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  api_calls:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Llamada a la primera API (The Cat API)
      - name: Make first API request (The Cat API)
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p api_responses
          curl -s "https://api.thecatapi.com/v1/images/search" -o api_responses/cat_image_$TIMESTAMP.json

      # Paso 3: Llamada a la segunda API (Random User Generator)
      - name: Make second API request (Random User Generator)
        run: |
          USER_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          curl -s "https://randomuser.me/api/" -o api_responses/random_user_$USER_TIMESTAMP.json

      # Paso 4: Commit y Push de las respuestas de las API
      - name: Commit and push API responses
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Alvaro"
          git config --global user.email "17alma41@gmail.com"
          git add api_responses/ || echo "No hay cambios en api_responses"
          git diff --cached --quiet || (git commit -m "Nueva llamada a la API - $TIMESTAMP y datos de usuario aleatorio" && git push origin main)

      # Paso 5: Enviar mensaje a Telegram
      - name: Send Telegram message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
               -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
               -d text="API Requests completed. New response saved: Cat image and random user data at $USER_TIMESTAMP"
