name: Random User API Call

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos
  workflow_dispatch:  

jobs:
  api_calls:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Llamada a la API (Random User Generator)
      - name: Make API request (Random User Generator)
        run: |
          USER_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p api_responses
          curl -s "https://randomuser.me/api/" -o api_responses/random_user_$USER_TIMESTAMP.json

      # Commit y Push de la respuesta de la API
      - name: Commit and push API response
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Alvaro"
          git config --global user.email "17alma41@gmail.com"
          git add api_responses/ || echo "No hay cambios en api_responses"
          git diff --cached --quiet || (git commit -m "Nueva llamada a la API - $USER_TIMESTAMP y datos de usuario aleatorio" && git push origin main)

      # Enviar mensaje a Telegram
      - name: Send Telegram message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
               -d chat_id="${{ secrets.CHAT_ID }}" \
               -d text="API Request completed. New random user data saved at $USER_TIMESTAMP"
