name: Llamada a la API

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # La acción se ejecuta cada 5 minutos

jobs:
  api_call:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Llamada a la API y guardar resultado
        run: |
          # Definir la URL de la API de OpenWeatherMap (usamos una ciudad de ejemplo)
          CITY="London"
          API_KEY="${{ secrets.OPENWEATHER_API_KEY }}"
          API_URL="https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=$API_KEY&units=metric"
          
          # Obtener la respuesta de la API y guardarla en una variable
          API_RESPONSE=$(curl -s $API_URL)

          # Verificar si la llamada a la API fue exitosa
          if [ $? -ne 0 ]; then
            echo "Error al realizar la llamada a la API"
            exit 1
          fi

          # Obtener la hora actual en formato YYYY-MM-DD_HH-MM-SS para el nombre del archivo
          CURRENT_TIME=$(date '+%Y-%m-%d_%H-%M-%S')

          # Guardar el resultado de la API en un archivo con el nombre basado en la hora
          echo "$API_RESPONSE" > "weather_response_$CURRENT_TIME.json"

          # Configuración de Git
          git config --global user.name "Alvaro"
          git config --global user.email "17alma41@gmail.com"
          git add "weather_response_$CURRENT_TIME.json"  # Añadir el nuevo archivo de respuesta
          git commit -m "Nuevo archivo de respuesta API - $CURRENT_TIME"

          # Hacer push del nuevo archivo al repositorio
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      - name: Enviar mensaje a Telegram con respuesta de la API
        run: |
          TOKEN="${{ secrets.BOT_TOKEN }}"
          CHAT_ID="${{ secrets.CHAT_ID }}"
          MESSAGE="La respuesta de la API del clima en $CITY es: $API_RESPONSE"
          
          # Enviar el mensaje a Telegram
          curl -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
              -d chat_id=$CHAT_ID \
              -d text="$MESSAGE"
